[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.28.0"

[profile.dev]
opt-level = 1

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false
